config/routes.rb
Rails.application.routes.draw do

scope '(:locale)', locale: /ua|ru/ do
    resources :contact_us
    resources :contacts, only: [:new, :create, :edit, :update, :index, :destroy]  
    root :to => 'main_shots#index'

    get 'password_resets/new'

    get 'password_resets/edit'

    get 'sessions/new'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]


    get  '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'  
    resources :users
    resources :reservations, only: [:index, :edit, :update, :show, :destroy]
    resources :entertainments
    resources :main_shots
    resources :booking_posts do
      resources :booking_pictures
      resources :reservations, only: [:new, :create]
    end

    resources :albums do
    	resources :images
    end
    resources :post_slides
    resources :posts

    patch 'posts/:id', controller: 'posts', action: :update

    match '/test',                    to: 'static_pages#test',                  via: 'get'
    match '/test2',                    to: 'static_pages#test2',                  via: 'get'
    match '/paralax',                    to: 'static_pages#paralax',                  via: 'get'
end
end

app/models/booking_post.rb
class BookingPost < ApplicationRecord
	has_many :booking_pictures, dependent: :destroy
	has_many :reservations, dependent: :destroy
end

app/controllers/booking_posts_controller.rb
class BookingPostsController < ApplicationController
  before_action :set_booking_post, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:new, :create, :edit, :update, :destroy]
  
  # GET /booking_posts
  def index
    @booking_posts = BookingPost.all.paginate(:page => params[:page], :per_page => 10).order('created_at DESC')
  end

  # GET /booking_posts/1
  def show
    @booking_picture = @booking_post.booking_pictures.build
    @booking_pictures = @booking_post.booking_pictures
    @reservation = @booking_post.reservations.build
    @reservations = @booking_post.reservations
  end

  # GET /booking_posts/new
  def new
    @booking_post = BookingPost.new
  end

  # GET /booking_posts/1/edit
  def edit
  end

  # POST /booking_posts
  def create
    @booking_post = BookingPost.new(booking_post_params)

    respond_to do |format|
      if @booking_post.save
        format.html { redirect_to @booking_post, notice: 'Booking post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /booking_posts/1
  def update
    respond_to do |format|
      if @booking_post.update(booking_post_params)
        format.html { redirect_to @booking_post, notice: 'Booking post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /booking_posts/1
  def destroy
    @booking_post.destroy
    respond_to do |format|
      format.html { redirect_to booking_posts_url, notice: 'Booking post was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking_post
      @booking_post = BookingPost.find(params[:id])
    end

    def admin_user
      redirect_to(booking_posts_path) unless current_user.present? and current_user.admin?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_post_params
      params.require(:booking_post).permit(:title, :description, :title2, :description2)
    end
end

app/views/booking_posts/_form.html.erb
<div class="container">
<% if current_user.present? and current_user.admin? %>
<%= form_for(booking_post, html: {multipart: true}, class: "col s12") do |f| %>
  <% if booking_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking_post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% booking_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="input-field col s6">
    <%= f.label :title %>
    <%= f.text_field :title, class: "validate" %>
  </div>

   <div class="input-field col s6">
    <%= f.label :description %>
    <%= f.text_area :description, id: "textarea1", class: "materialize-textarea" %>
  </div>
  <div class="input-field col s6">
    <%= f.label :title2 %>
    <%= f.text_field :title2, class: "validate" %>
  </div>

   <div class="input-field col s6">
    <%= f.label :description2 %>
    <%= f.text_area :description2, id: "textarea1", class: "materialize-textarea" %>
  </div>

  <div class="waves-effect waves-light btn">
    <%= f.submit "OK" %>
  </div>  
  
<% end %>
<% end %>
</div>

app/views/booking_posts/edit.html.erb
<h2 class="center"><%= t(".title")%></h2>

<%= render 'form', booking_post: @booking_post %>
<br>
<div class="container center">
	<%= link_to t(:show), @booking_post, class: "waves-effect waves-light btn" %> 
	<%= link_to t(:back), booking_posts_path, class: "waves-effect waves-light btn"  %>
</div>

app/views/booking_posts/index.html.erb
<style type="text/css">
  .pagination li.active {
    background: grey;
}
  .pagination li a:hover {
    background: #eeeeee;
  }

  .slider .indicators .indicator-item.active {
    background-color: grey;
  }

</style>
<p id="notice"><%= notice %></p>



<% if current_user.present? and current_user.admin? %>
<div class="container center">
  <%= link_to t(".add"), new_booking_post_path, class: "waves-effect waves-light btn midle" %>
</div>
<% end %>
</br>
<div class="container">    
    <% @booking_posts.each do |booking_post| %>
    <% if current_page?(locale: :ua) %>
      <div class="row">
        <div class="col s12 m8 offset-m2 ">
          <div class="card hoverable">
            <div class="card-image">
              <div class="slider">
                <ul class="slides">
                <% booking_post.booking_pictures.each do |pic| %>
                <%if pic.photo.present?%>
                  <li>
                    <%= image_tag pic.photo.url(:large)%>
                    <% if current_user.present? and current_user.admin? %>
                      <div class="caption center-align", style="color: black;">
                        <h5><%= link_to t(:destroy), [pic.booking_post, pic], class: "waves-effect waves-light btn red", method: :delete, data: { confirm: 'Are you sure?' } %></h5>
                      </div>
                    <% end %>
                  </li>
                <%end%>
                <% end %>
                </ul>
              </div>
            </div>
            <div class="card-content">
            <span class="card-title truncate"><td><%= booking_post.title %></td></span>
              <p><%= truncate(simple_format(booking_post.description), escape: false, length: 300)%></p>
            </div>
            <div class="card-action">
              <%= link_to t(:details), booking_post_path(booking_post) %>
              <% if current_user.present? and current_user.admin? %>
              <%= link_to t(:edit), edit_booking_post_path(booking_post) %>
              <%= link_to t(:destroy), booking_post, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% elsif current_page?(locale: :ru) %>
      <div class="row">
        <div class="col s12 m8 offset-m2 ">
          <div class="card hoverable">
            <div class="card-image">
              <div class="slider">
                <ul class="slides">
                <% booking_post.booking_pictures.each do |pic| %>
                <%if pic.photo.present?%>
                  <li>
                    <%= image_tag pic.photo.url(:large)%>
                    <% if current_user.present? and current_user.admin? %>
                      <div class="caption center-align", style="color: black;">
                        <h5><%= link_to t(:destroy), [pic.booking_post, pic], class: "waves-effect waves-light btn red", method: :delete, data: { confirm: 'Are you sure?' } %></h5>
                      </div>
                    <% end %>
                  </li>
                <%end%>
                <% end %>
                </ul>
              </div>
            </div>
            <div class="card-content">
            <span class="card-title truncate"><td><%= booking_post.title2 %></td></span>
              <p><%= truncate(simple_format(booking_post.description2), escape: false, length: 300)%></p>
            </div>
            <div class="card-action">
              <%= link_to t(:details), booking_post_path(booking_post) %>
              <% if current_user.present? and current_user.admin? %>
              <%= link_to t(:edit), edit_booking_post_path(booking_post) %>
              <%= link_to t(:destroy), booking_post, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </div>
          </div>
        </div>
      </div>    
    <% end %>
    <% end %>
</div>
<br>
<div class="center">
<%= will_paginate @booking_posts %>
</div>
<br>
<% if current_user.present? and current_user.admin? %>
<div class="container center">
<%= link_to t(".add"), new_booking_post_path, class: "waves-effect waves-light btn midle" %>
</div>
<% end %>

app/views/booking_posts/new.html.erb
<h2 class="center"><%= t(".title")%></h2>

<%= render 'form', booking_post: @booking_post %>

<br>
<div class="container center">
	<%= link_to t(:back), booking_posts_path, class: "waves-effect waves-light btn "  %>
</div>

app/views/booking_posts/show.html.erb
<style>
  .slider .indicators .indicator-item.active {
    background-color: grey;
  }
</style>
<p id="notice"><%= notice %></p>
<br>
<div class="row">
  <div class="col s12 m6 offset-m3 ">
    <div class="card hoverable">

      <div class="slider">
        <ul class="slides">
        <% @booking_pictures.each do |pic| %>
          <%if pic.photo.present?%>
            <li>
              <%= image_tag pic.photo.url(:large)%>
              <% if current_user.present? and current_user.admin? %>
                <div class="caption center-align", style="color: black;">
                  <h5><%= link_to t(:destroy), [pic.booking_post, pic], class: "waves-effect waves-light btn red", method: :delete, data: { confirm: 'Are you sure?' }  %></h5>
                </div>
              <% end %>
            </li>
          <%end%>
        <% end %>
        </ul>
      </div>
      <% if current_page?(locale: :ua) %>
      <div class="card-content">
        <span class="card-title truncate"><td><%= @booking_post.title %></td></span>
        <p><%= simple_format(@booking_post.description)%></p>
      </div>
      <% elsif current_page?(locale: :ru) %>
      <div class="card-content">
        <span class="card-title truncate"><td><%= @booking_post.title2 %></td></span>
        <p><%= simple_format(@booking_post.description2)%></p>
      </div>  
      <% end %>
      <br>

      <% if current_user.present? and current_user.admin? %>
        <div class="card-action">
          <%= form_for([@booking_picture.booking_post, @booking_picture], html: {multipart: true}, class: "col s12") do |f| %>
            <% if @booking_picture.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@booking_picture.errors.count, "error") %> prohibited this post from being saved:</h2>

                <ul>
                <% @booking_picture.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <div class="file-field input-field">
              <div class="btn">
                <span><%= t(:booking_picture)%></span>
                <%= f.file_field :photo %>
              </div>
              <div class="file-path-wrapper">
                <input class="file-path validate" type="text">
              </div>
            </div>

            <div class="waves-effect waves-light btn">
              <%= f.submit t(:add_booking_picture)%>
            </div>  
        
          <% end %>
        </div>
      <% end %>   

      <!-- reserve -->
      <div class="card-action">
        <%= form_for([@reservation.booking_post, @reservation], html: {multipart: true}, class: "col s12") do |f| %>
        <% if @reservation.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this post from being saved:</h2>

            <ul>
            <% @reservation.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="col s6">
          <%= f.label :date %>
          <%= f.date_field :start, class: "datepicker" %>
        </div>
        <div class="col s6">
          <%= f.label :reservation_time %>
          <%= f.time_field :reservation_time, placeholder: "time", class: "timepicker", id: "timepicker", type: "time" %>
        </div>
        <div class="input-field col s6">
          <%= f.label :name %>
          <%= f.text_field :name, class: "validate" %>
        </div>
        <div class="input-field col s6">
          <%= f.label :email %>
          <%= f.text_field :email, class: "validate" %>
        </div>
        <div class="input-field col s6">
          <%= f.label :phone_number %>
          <%= f.text_field :phone_number, class: "validate" %>
        </div>

        <div class="waves-effect waves-light btn">
          <%= f.submit t(:submit_reservation)%>
        </div>  
        
        <% end %>
        
        <br>

      </div>


        <!-- reserves -->

        <div class="card-action">
          <h5><%= t(:booked_title)%></h5>
          <% @reservations.each do |r| %>
            <% if r.start.present? %>
            <br>
              <%= r.start.to_s%>
              <%= r.reservation_time.strftime("%H:%M")%>
            <% end %>
          <% end %>
        </div>


        <!---------------------->
      <br>
    </div>
  </div>
</div>


<div class="container center">
	 
	<%= link_to t(:back), booking_posts_path, class: "waves-effect waves-light btn grey lighten-3"  %>
  <% if current_user.present? and current_user.admin? %>
  <%= link_to t(:edit), edit_booking_post_path(@booking_post), class: "waves-effect waves-light btn" %>
	<%= link_to t(:destroy), @booking_post, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn red" %>
  <% end %>
</div>

<script src="https://cdn.rawgit.com/chingyawhao/materialize-clockpicker/master/dist/js/materialize.clockpicker.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/chingyawhao/materialize-clockpicker/master/dist/css/materialize.clockpicker.css">

<script>
    $(document).ready(function () {
       
    });

    $('.timepicker').pickatime({
      default: 'now',
      twelvehour: false, // change to 12 hour AM/PM clock from 24 hour
      donetext: 'OK',
      autoclose: false,
      vibrate: true // vibrate the device when dragging clock hand
    });
              
</script>