config/routes.rb
Rails.application.routes.draw do

scope '(:locale)', locale: /ua|ru/ do
    resources :contact_us
    resources :contacts, only: [:new, :create, :edit, :update, :index, :destroy]  
    root :to => 'main_shots#index'

    get 'password_resets/new'

    get 'password_resets/edit'

    get 'sessions/new'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]


    get  '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'  
    resources :users
    resources :reservations, only: [:index, :edit, :update, :show, :destroy]
    resources :entertainments
    resources :main_shots
    resources :booking_posts do
      resources :booking_pictures
      resources :reservations, only: [:new, :create]
    end

    resources :albums do
    	resources :images
    end
    resources :post_slides
    resources :posts

    patch 'posts/:id', controller: 'posts', action: :update

    match '/test',                    to: 'static_pages#test',                  via: 'get'
    match '/test2',                    to: 'static_pages#test2',                  via: 'get'
    match '/paralax',                    to: 'static_pages#paralax',                  via: 'get'
end
end

app/models/post_slide.rb
class PostSlide < ApplicationRecord
	has_attached_file :photo, styles: { large: "500x500>", very_large: "600x600>", def: "1280x1280>"}, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  	belongs_to :position
  	validates :position, presence: true
end

app/controllers/post_slides_controller.rb
class PostSlidesController < ApplicationController
  before_action :set_post_slide, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:new, :create, :edit, :update, :destroy, :show, :index]
  
  # GET /post_slides
  def index
    @post_slides = PostSlide.all.order(created_at: :desc)
  end

  # GET /post_slides/1
  def show
  end

  # GET /post_slides/new
  def new
    @post_slide = PostSlide.new
  end

  # GET /post_slides/1/edit
  def edit
  end

  # POST /post_slides
  def create
    @post_slide = PostSlide.new(post_slide_params)

    respond_to do |format|
      if @post_slide.save
        format.html { redirect_to post_slides_path, notice: 'Post slide was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /post_slides/1
  def update
    respond_to do |format|
      if @post_slide.update(post_slide_params)
        format.html { redirect_to @post_slide, notice: 'Post slide was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /post_slides/1
  def destroy
    @post_slide.photo = nil
    @post_slide.save
    @post_slide.destroy
    respond_to do |format|
      format.html { redirect_to post_slides_url, notice: 'Post slide was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_slide
      @post_slide = PostSlide.find(params[:id])
    end
    def admin_user
      redirect_to(root_url) unless current_user.present? and current_user.admin?
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_slide_params
      params.require(:post_slide).permit(:description, :position_id, :photo, :title, :black, :title2, :description2)
    end
end

app/views/post_slides/_form.html.erb
<div class="container">
<% if current_user.present? and current_user.admin? %>
<%= form_for(post_slide, html: {multipart: true}, class: "col s12") do |f| %>
  <% if post_slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post_slide.errors.count, "error") %> prohibited this post_slide from being saved:</h2>

      <ul>
      <% post_slide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="input-field col s12">
    <%= f.label :title %>
    <%= f.text_field :title, class: "validate" %>
  </div>

  <div class="input-field col s12">
    <%= f.label :title2 %>
    <%= f.text_field :title2, class: "validate" %>
  </div>

  <div class="input-field col s12">
    <%= f.label :description %>
    <%= f.text_field :description, class: "validate" %>
  </div>

  <div class="input-field col s12">
    <%= f.label :description2 %>
    <%= f.text_field :description2, class: "validate" %>
  </div>
  
  <div class="input-field col s6">
  
  <%= collection_select :post_slide, :position_id, Position.all, :id, :align, {prompt: "select position"} %>
  </div>

  <div class="input-field col s6">
    <%= f.check_box :black, id: "test5" %>
    <%= f.label (:black), for: "test5"  %> 
  </div>

  <div class="file-field input-field">
      <div class="btn">
        <span><%= t(:photo)%></span>
        <%= f.file_field :photo %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
  </div>

  <div class="waves-effect waves-light btn">
    <%= f.submit t(:submit_post_slide) %>
  </div>  
<% end %>

<% end %>
</div>
<script>
    $('select').material_select();
</script>

app/views/post_slides/edit.html.erb
<h2 class="center"><%= t(".title") %></h2>

<%= render 'form', post_slide: @post_slide %>

<br>
<div class="container center">
	<%= link_to t(:show), @post_slide, class: "waves-effect waves-light btn" %> 
	<%= link_to t(:back), post_slides_path, class: "waves-effect waves-light btn"  %>
</div>

app/views/post_slides/index.html.erb
<style>
  .slider .indicators .indicator-item.active {
    background-color: grey;
  }
</style>
<% if current_user.present? and current_user.admin? %>
<p id="notice"><%= notice %></p>
<% if current_page?(locale: :ua) %>
  <div class="slider">
    <ul class="slides">
    <% @post_slides.each do |post_slide| %>
      <li>
      <% if post_slide.photo.present?%>
        <%= image_tag post_slide.photo.url(:large)%>
        <%if post_slide.position.align == "left" %>
          
        <%if post_slide.black == true%>
          <div class="caption left-align", style="color: black;">
            <h3><%= post_slide.title %></h3>
            <h5><%= post_slide.description%></h5>
          </div>
        <%else%>
          <div class="caption left-align">
            <h3><%= post_slide.title %></h3>
            <h5 class="light grey-text text-lighten-3"><%= post_slide.description%></h5>
              <div>
              <%= link_to t(:details), post_slide_path(post_slide), class: "waves-effect waves-light btn" %>
              <%= link_to t(:edit), edit_post_slide_path(post_slide), class: "waves-effect waves-light btn" %>
              <%= link_to t(:destroy), post_slide, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn red" %>
              </div>
          </div>
        <%end%>

        <%elsif post_slide.position.align == "center" %>
          
        <%if post_slide.black == true%>
          <div class="caption center-align", style="color: black;">
            <h3><%= post_slide.title %></h3>
            <h5><%= post_slide.description%></h5>
          </div>
        <%else%>
          <div class="caption center-align">
            <h3><%= post_slide.title %></h3>
            <h5 class="light grey-text text-lighten-3"><%= post_slide.description%></h5>
           ]  <div>
              <%= link_to t(:details), post_slide_path(post_slide), class: "waves-effect waves-light btn" %>
              <%= link_to t(:edit), edit_post_slide_path(post_slide), class: "waves-effect waves-light btn" %>
              <%= link_to t(:destroy), post_slide, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn red" %>
              </div>
          </div>
        <%end%>

        <%elsif post_slide.position.align == "right"%>
          
        <%if post_slide.black == true%>
          <div class="caption right-align", style="color: black;">
            <h3><%= post_slide.title %></h3>
            <h5><%= post_slide.description%></h5>
          </div>
        <%else%>
          <div class="caption right-align">
            <h3><%= post_slide.title %></h3>
            <h5 class="light grey-text text-lighten-3"><%= post_slide.description%></h5>
              <div>
              <%= link_to t(:details), post_slide_path(post_slide), class: "waves-effect waves-light btn" %>
              <%= link_to t(:edit), edit_post_slide_path(post_slide), class: "waves-effect waves-light btn" %>
              <%= link_to t(:destroy), post_slide, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn red" %>
              </div>
          </div>
        <%end%>

        <%end%>
      <% end %>
      </li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if current_page?(locale: :ru) %>
  <div class="slider">
    <ul class="slides">
    <% @post_slides.each do |post_slide| %>
      <li>
      <% if post_slide.photo.present?%>
        <%= image_tag post_slide.photo.url(:large)%>
        <%if post_slide.position.align == "left" %>
          
        <%if post_slide.black == true%>
          <div class="caption left-align", style="color: black;">
            <h3><%= post_slide.title2 %></h3>
            <h5><%= post_slide.description2%></h5>
            <div>
              <%= link_to t(:details), post_slide_path(post_slide), class: "waves-effect waves-light btn" %>
              <%= link_to t(:edit), edit_post_slide_path(post_slide), class: "waves-effect waves-light btn" %>
              <%= link_to t(:destroy), post_slide, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn red" %>
            </div>
          </div>
        <%else%>
          <div class="caption left-align">
            <h3><%= post_slide.title2 %></h3>
            <h5 class="light grey-text text-lighten-3"><%= post_slide.description2%></h5>
              <div>
              <%= link_to t(:details), post_slide_path(post_slide), class: "waves-effect waves-light btn" %>
              <%= link_to t(:edit), edit_post_slide_path(post_slide), class: "waves-effect waves-light btn" %>
              <%= link_to t(:destroy), post_slide, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn red" %>
              </div>
          </div>
        <%end%>

        <%elsif post_slide.position.align == "center" %>
          
        <%if post_slide.black == true%>
          <div class="caption center-align", style="color: black;">
            <h3><%= post_slide.title2 %></h3>
            <h5><%= post_slide.description2%></h5>
            <div>
              <%= link_to t(:details), post_slide_path(post_slide), class: "waves-effect waves-light btn" %>
              <%= link_to t(:edit), edit_post_slide_path(post_slide), class: "waves-effect waves-light btn" %>
              <%= link_to t(:destroy), post_slide, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn red" %>
            </div>
          </div>
        <%else%>
          <div class="caption center-align">
            <h3><%= post_slide.title2 %></h3>
            <h5 class="light grey-text text-lighten-3"><%= post_slide.description2%></h5>
            <div>
              <%= link_to t(:details), post_slide_path(post_slide), class: "waves-effect waves-light btn" %>
              <%= link_to t(:edit), edit_post_slide_path(post_slide), class: "waves-effect waves-light btn" %>
              <%= link_to t(:destroy), post_slide, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn red" %>
            </div>
          </div>
        <%end%>

        <%elsif post_slide.position.align == "right"%>
          
        <%if post_slide.black == true%>
          <div class="caption right-align", style="color: black;">
            <h3><%= post_slide.title2 %></h3>
            <h5><%= post_slide.description2%></h5>
            <div>
              <%= link_to t(:details), post_slide_path(post_slide), class: "waves-effect waves-light btn" %>
              <%= link_to t(:edit), edit_post_slide_path(post_slide), class: "waves-effect waves-light btn" %>
              <%= link_to t(:destroy), post_slide, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn red" %>
            </div>
          </div>
        <%else%>
          <div class="caption right-align">
            <h3><%= post_slide.title2 %></h3>
            <h5 class="light grey-text text-lighten-3"><%= post_slide.description2%></h5>
            <div>
              <%= link_to t(:details), post_slide_path(post_slide), class: "waves-effect waves-light btn" %>
              <%= link_to t(:edit), edit_post_slide_path(post_slide), class: "waves-effect waves-light btn" %>
              <%= link_to t(:destroy), post_slide, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn red" %>
            </div>
          </div>
        <%end%>

        <%end%>
      <% end %>
      </li>
      <% end %>
    </ul>
  </div>
<% end %>



<div class="container center">
<%= link_to t(".add"), new_post_slide_path, class: "waves-effect waves-light btn midle" %>
</div>
<% end %>

app/views/post_slides/new.html.erb
<h2 class="center"><%= t(".title") %></h2>

<%= render 'form', post_slide: @post_slide %>

<br>
<div class="container center">
	<%= link_to t(:back), post_slides_path, class: "waves-effect waves-light btn "  %>
</div>

app/views/post_slides/show.html.erb
<% if current_user.present? and current_user.admin? %>
  <p id="notice"><%= notice %></p>
<% if current_page?(locale: :ua) %>
  <div class="row">
      <div class="col s12 m6 offset-m3 ">
        <div class="card hoverable">
          <div class="card-image">
            <%= image_tag @post_slide.photo.url(:large) %>
              <%if @post_slide.black == true%>
                <span class="card-title truncate", style="color: black;"><td><%= @post_slide.title %></td></span>
              <%else%>
                <span class="card-title truncate"><td><%= @post_slide.title %></td></span>
              <%end%>      
          </div>
          <div class="card-content">
            <p><%= simple_format(@post_slide.description)%></p>
          </div>
        </div>
      </div>
    </div>
<% end %>
<% if current_page?(locale: :ru) %>
  <div class="row">
      <div class="col s12 m6 offset-m3 ">
        <div class="card hoverable">
          <div class="card-image">
            <%= image_tag @post_slide.photo.url(:large) %>
              <%if @post_slide.black == true%>
                <span class="card-title truncate", style="color: black;"><td><%= @post_slide.title2 %></td></span>
              <%else%>
                <span class="card-title truncate"><td><%= @post_slide.title2 %></td></span>
              <%end%>      
          </div>
          <div class="card-content">
            <p><%= simple_format(@post_slide.description2)%></p>
          </div>
        </div>
      </div>
    </div>
<% end %>
  <div class="container center">
  	<%= link_to t(:edit), edit_post_slide_path(@post_slide), class: "waves-effect waves-light btn" %> 
  	<%= link_to t(:back), post_slides_path, class: "waves-effect waves-light btn"  %>
  	<%= link_to t(:destroy), @post_slide, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn red" %>
  </div>
<% end %>