config/routes.rb
Rails.application.routes.draw do

scope '(:locale)', locale: /ua|ru/ do
    resources :contact_us
    resources :contacts, only: [:new, :create, :edit, :update, :index, :destroy]  
    root :to => 'main_shots#index'

    get 'password_resets/new'

    get 'password_resets/edit'

    get 'sessions/new'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]


    get  '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'  
    resources :users
    resources :reservations, only: [:index, :edit, :update, :show, :destroy]
    resources :entertainments
    resources :main_shots
    resources :booking_posts do
      resources :booking_pictures
      resources :reservations, only: [:new, :create]
    end

    resources :albums do
    	resources :images
    end
    resources :post_slides
    resources :posts

    patch 'posts/:id', controller: 'posts', action: :update

    match '/test',                    to: 'static_pages#test',                  via: 'get'
    match '/test2',                    to: 'static_pages#test2',                  via: 'get'
    match '/paralax',                    to: 'static_pages#paralax',                  via: 'get'
end
end

app/models/post.rb
class Post < ApplicationRecord
	has_attached_file :photo, styles: { medium: "300x300>", large: "500x500>", very_large: "600x600>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:new, :create, :edit, :update, :destroy]
  
  # GET /posts
  def index
    @posts = Post.all.paginate(:page => params[:page], :per_page => 10).order('created_at DESC')
    @post_slides = PostSlide.all.order(created_at: :desc)
  end

  # GET /posts/1
  def show
    @post_slides = PostSlide.all.order(created_at: :desc)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1
  def destroy
    @post.photo = nil
    @post.save
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end
    def admin_user
      redirect_to(posts_path) unless current_user.present? and current_user.admin?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :title, :photo, :black, :title2, :description2)
    end
end

app/views/posts/_form.html.erb
<div class="container">
<% if current_user.present? and current_user.admin? %>
<%= form_for(post, html: {multipart: true}, class: "col s12") do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="input-field col s6">
    <%= f.label (:title) %>
    <%= f.text_field :title, class: "validate" %>
  </div>
  <div class="input-field col s6">
    <%= f.label (:title2) %>
    <%= f.text_field :title2, class: "validate" %>
  </div>
  <div>
    <%= f.check_box :black, id: "test5" %>
    <%= f.label (:black), for: "test5"  %>
  </div>
  <div class="input-field col s6">
    <%= f.label :description %>
    <%= f.text_area :description, id: "textarea1", class: "materialize-textarea" %>
  </div>
  <div class="input-field col s6">
    <%= f.label :description2 %>
    <%= f.text_area :description2, id: "textarea1", class: "materialize-textarea" %>
  </div>
  <div class="file-field input-field">
      <div class="btn">
        <span><%= t(:photo) %></span>
        <%= f.file_field :photo %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>

  <div class="waves-effect waves-light btn">
    <%= f.submit "OK" %>
  </div>  
  
<% end %>
<% end %>

</div>

app/views/posts/edit.html.erb
<h2 class="center"><%= t(".title")%></h2>

<%= render 'form', post: @post %>
<br>
<div class="container center">
	<%= link_to t(:edit), @post, class: "waves-effect waves-light btn" %> 
	<%= link_to t(:back), posts_path, class: "waves-effect waves-light btn"  %>
</div>

app/views/posts/index.html.erb
<style type="text/css">
  .pagination li.active {
    background: grey;
}
  .pagination li a:hover {
    background: #eeeeee;
  }


  .slider .indicators .indicator-item.active {
    background-color: grey;
  }

</style>
<p id="notice"><%= notice %></p>
<% if current_page?(locale: :ua) %>
<div>
  <div class="slider">
    <ul class="slides">
    <% @post_slides.each do |post_slide| %>
      <% if post_slide.photo.present?%>
      <li>
        <%= image_tag post_slide.photo.url(:large)%>
        <%if post_slide.position.present? %>
            <%if post_slide.position.align == "left" %>
              
            <%if post_slide.black == true%>
              <div class="caption left-align", style="color: black;">
                <h3><%= post_slide.title %></h3>
                <h5><%= post_slide.description%></h5>
              </div>
            <%else%>
              <div class="caption left-align">
                <h3><%= post_slide.title %></h3>
                <h5 class="light grey-text text-lighten-3"><%= post_slide.description%></h5>
              </div>
            <%end%>

            <%elsif post_slide.position.align == "center" %>
              
            <%if post_slide.black == true%>
              <div class="caption center-align", style="color: black;">
                <h3><%= post_slide.title %></h3>
                <h5><%= post_slide.description%></h5>
              </div>
            <%else%>
              <div class="caption center-align">
                <h3><%= post_slide.title %></h3>
                <h5 class="light grey-text text-lighten-3"><%= post_slide.description%></h5>
              </div>
            <%end%>

            <%elsif post_slide.position.align == "right"%>
              
            <%if post_slide.black == true%>
              <div class="caption right-align", style="color: black;">
                <h3><%= post_slide.title %></h3>
                <h5><%= post_slide.description%></h5>
              </div>
            <%else%>
              <div class="caption right-align">
                <h3><%= post_slide.title %></h3>
                <h5 class="light grey-text text-lighten-3"><%= post_slide.description%></h5>
              </div>
            <%end%>
          <%end%>
        <%end%>
          
      
      <%end%>
      </li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<% if current_page?(locale: :ru) %>
<div>
  <div class="slider">
    <ul class="slides">
    <% @post_slides.each do |post_slide| %>
      <% if post_slide.photo.present?%>
      <li>
        <%= image_tag post_slide.photo.url(:large)%>
        <%if post_slide.position.present? %>
          <%if post_slide.position.align == "left" %>
            
          <%if post_slide.black == true%>
            <div class="caption left-align", style="color: black;">
              <h3><%= post_slide.title2 %></h3>
              <h5><%= post_slide.description2%></h5>
            </div>
          <%else%>
            <div class="caption left-align">
              <h3><%= post_slide.title2 %></h3>
              <h5 class="light grey-text text-lighten-3"><%= post_slide.description2%></h5>
            </div>
          <%end%>

          <%elsif post_slide.position.align == "center" %>
            
          <%if post_slide.black == true%>
            <div class="caption center-align", style="color: black;">
              <h3><%= post_slide.title2 %></h3>
              <h5><%= post_slide.description2%></h5>
            </div>
          <%else%>
            <div class="caption center-align">
              <h3><%= post_slide.title2 %></h3>
              <h5 class="light grey-text text-lighten-3"><%= post_slide.description2%></h5>
            </div>
          <%end%>

          <%elsif post_slide.position.align == "right"%>
            
          <%if post_slide.black == true%>
            <div class="caption right-align", style="color: black;">
              <h3><%= post_slide.title2 %></h3>
              <h5><%= post_slide.description2%></h5>
            </div>
          <%else%>
            <div class="caption right-align">
              <h3><%= post_slide.title2 %></h3>
              <h5 class="light grey-text text-lighten-3"><%= post_slide.description2%></h5>
            </div>
          <%end%>

        <%end%>
        <%end%>
              
      <%end%>
      </li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<% if current_user.present? and current_user.admin? %>  
  <%= link_to t('.edit_slider'), post_slides_path, class: "waves-effect waves-light btn"  %>
<% end %>


<% if current_user.present? and current_user.admin? %>
  <div class="container center">
    <%= link_to t('.add'), new_post_path, class: "waves-effect waves-light btn midle" %>
  </div>
<% end %>

</br>

<% if current_page?(locale: :ua) %>
<div class="container">    
    <% @posts.each do |post| %>
      <div class="row">
        <div class="col s12 m8 offset-m2">
          <div class="card hoverable">
            <div class="card-image">
              <%= image_tag post.photo.url(:large) %>
              <%if post.black == true%>
              <span class="card-title truncate", style="color: black;"><td><%= post.title %></td></span>
              <%else%>
              <span class="card-title truncate"><td><%= post.title %></td></span>
              <%end%>            
            </div>
            <div class="card-content">

              <p><%= truncate(simple_format(post.description), escape: false, length: 300) %></p>
            </div>
            <div class="card-action">
              <%= link_to t(:details), post_path(post) %>
              <%= link_to t(:edit), edit_post_path(post) if current_user.present? and current_user.admin? %>
              <%= link_to t(:destroy), post, method: :delete, data: { confirm: 'Are you sure?' } if current_user.present? and current_user.admin? %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
</div>
<% end %>

<% if current_page?(locale: :ru) %>
<div class="container">    
    <% @posts.each do |post| %>
      <div class="row">
        <div class="col s12 m8 offset-m2">
          <div class="card hoverable">
            <div class="card-image">
              <%= image_tag post.photo.url(:large) %>
              <%if post.black == true%>
              <span class="card-title truncate", style="color: black;"><td><%= post.title2 %></td></span>
              <%else%>
              <span class="card-title truncate"><td><%= post.title2 %></td></span>
              <%end%>            
            </div>
            <div class="card-content">

              <p><%= truncate(simple_format(post.description2), escape: false, length: 300) %></p>
            </div>
            <div class="card-action">
              <%= link_to t(:details), post_path(post) %>
              <%= link_to t(:edit), edit_post_path(post) if current_user.present? and current_user.admin? %>
              <%= link_to t(:destroy), post, method: :delete, data: { confirm: 'Are you sure?' } if current_user.present? and current_user.admin? %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
</div>
<% end %>
<br>
<div class="center">
<%= will_paginate @posts %>
</div>
<br>
<% if current_user.present? and current_user.admin? %>
  <div class="container center">
  <%= link_to t('.add'), new_post_path, class: "waves-effect waves-light btn midle" %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h2 class="center"><%=t(".title")%></h2>

<%= render 'form', post: @post %>
<br>
<div class="container center">
	<%= link_to t(:back), posts_path, class: "waves-effect waves-light btn "  %>
</div>

app/views/posts/show.html.erb
<style>
  .slider .indicators .indicator-item.active {
    background-color: grey;
  }
</style>
<p id="notice"><%= notice %></p>
<% if current_page?(locale: :ua) %>
  <div class="slider">
    <ul class="slides">
    <% @post_slides.each do |post_slide| %>
      <% if post_slide.photo.present? %>
      <li>
      <% if post_slide.photo.present?%>
        <%= image_tag post_slide.photo.url(:large)%>
        <%if post_slide.position.align == "left" %>
          
        <%if post_slide.black == true%>
          <div class="caption left-align", style="color: black;">
            <h3><%= post_slide.title %></h3>
            <h5><%= post_slide.description%></h5>
          </div>
        <%else%>
          <div class="caption left-align">
            <h3><%= post_slide.title %></h3>
            <h5 class="light grey-text text-lighten-3"><%= post_slide.description%></h5>
          </div>
        <%end%>

        <%elsif post_slide.position.align == "center" %>
          
        <%if post_slide.black == true%>
          <div class="caption center-align", style="color: black;">
            <h3><%= post_slide.title %></h3>
            <h5><%= post_slide.description%></h5>
          </div>
        <%else%>
          <div class="caption center-align">
            <h3><%= post_slide.title %></h3>
            <h5 class="light grey-text text-lighten-3"><%= post_slide.description%></h5>
          </div>
        <%end%>

        <%elsif post_slide.position.align == "right"%>
          
        <%if post_slide.black == true%>
          <div class="caption right-align", style="color: black;">
            <h3><%= post_slide.title %></h3>
            <h5><%= post_slide.description%></h5>
          </div>
        <%else%>
          <div class="caption right-align">
            <h3><%= post_slide.title %></h3>
            <h5 class="light grey-text text-lighten-3"><%= post_slide.description%></h5>
          </div>
        <%end%>

        <%end%>
      <% end %>
      </li>
      <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

<% if current_page?(locale: :ru) %>
  <div class="slider">
    <ul class="slides">
    <% @post_slides.each do |post_slide| %>
      <% if post_slide.photo.present? %>
      <li>
      <% if post_slide.photo.present?%>
        <%= image_tag post_slide.photo.url(:large)%>
        <%if post_slide.position.align == "left" %>
          
        <%if post_slide.black == true%>
          <div class="caption left-align", style="color: black;">
            <h3><%= post_slide.title2 %></h3>
            <h5><%= post_slide.description2%></h5>
          </div>
        <%else%>
          <div class="caption left-align">
            <h3><%= post_slide.title2 %></h3>
            <h5 class="light grey-text text-lighten-3"><%= post_slide.description2%></h5>
          </div>
        <%end%>

        <%elsif post_slide.position.align == "center" %>
          
        <%if post_slide.black == true%>
          <div class="caption center-align", style="color: black;">
            <h3><%= post_slide.title2 %></h3>
            <h5><%= post_slide.description2%></h5>
          </div>
        <%else%>
          <div class="caption center-align">
            <h3><%= post_slide.title2 %></h3>
            <h5 class="light grey-text text-lighten-3"><%= post_slide.description2%></h5>
          </div>
        <%end%>

        <%elsif post_slide.position.align == "right"%>
          
        <%if post_slide.black == true%>
          <div class="caption right-align", style="color: black;">
            <h3><%= post_slide.title2 %></h3>
            <h5><%= post_slide.description2%></h5>
          </div>
        <%else%>
          <div class="caption right-align">
            <h3><%= post_slide.title2 %></h3>
            <h5 class="light grey-text text-lighten-3"><%= post_slide.description2%></h5>
          </div>
        <%end%>

        <%end%>
      <% end %>
      </li>
      <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

<% if current_user.present? and current_user.admin? %>  
  <%= link_to t(".edit_slider"), post_slides_path, class: "waves-effect waves-light btn"  %>
<% end %>
<% if current_page?(locale: :ua) %>
<div class="row">
    <div class="col s12 m6 offset-m3 ">
      <div class="card hoverable">
        <div class="card-image">
          <%= image_tag @post.photo.url(:large) %>
            <%if @post.black == true%>
              <span class="card-title truncate", style="color: black;"><td><%= @post.title %></td></span>
            <%else%>
              <span class="card-title truncate"><td><%= @post.title %></td></span>
            <%end%>      
        </div>
        <div class="card-content">
          <p><%= simple_format(@post.description)%></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% if current_page?(locale: :ru) %>
<div class="row">
    <div class="col s12 m6 offset-m3 ">
      <div class="card hoverable">
        <div class="card-image">
          <%= image_tag @post.photo.url(:large) %>
            <%if @post.black == true%>
              <span class="card-title truncate", style="color: black;"><td><%= @post.title2 %></td></span>
            <%else%>
              <span class="card-title truncate"><td><%= @post.title2 %></td></span>
            <%end%>      
        </div>
        <div class="card-content">
          <p><%= simple_format(@post.description2)%></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

  <div class="container center">
    <%= link_to t(:back), posts_path, class: "waves-effect waves-light btn grey lighten-3"  %>
  	<% if current_user.present? and current_user.admin? %>
    <%= link_to t(:edit), edit_post_path(@post), class: "waves-effect waves-light btn" %> 
  	<%= link_to t(:destroy), @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn red" %>
    <% end %>
  </div>