config/routes.rb
Rails.application.routes.draw do

scope '(:locale)', locale: /ua|ru/ do
    resources :contact_us
    resources :contacts, only: [:new, :create, :edit, :update, :index, :destroy]  
    root :to => 'main_shots#index'

    get 'password_resets/new'

    get 'password_resets/edit'

    get 'sessions/new'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]


    get  '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'  
    resources :users
    resources :reservations, only: [:index, :edit, :update, :show, :destroy]
    resources :entertainments
    resources :main_shots
    resources :booking_posts do
      resources :booking_pictures
      resources :reservations, only: [:new, :create]
    end

    resources :albums do
    	resources :images
    end
    resources :post_slides
    resources :posts

    patch 'posts/:id', controller: 'posts', action: :update

    match '/test',                    to: 'static_pages#test',                  via: 'get'
    match '/test2',                    to: 'static_pages#test2',                  via: 'get'
    match '/paralax',                    to: 'static_pages#paralax',                  via: 'get'
end
end

app/views/layouts/_footer.html.erb
        <style>
         .page-footer {
          background-color: #eeeeee;
        <% if current_page?(contacts_path)%>  
          position: fixed;
        <% end %>  
          width: 100%;
          bottom: 0;
         }

        </style>

<% if @contact.present? %>
        <br>
        <footer class="page-footer">
          <div class="container">
            <div class="row grey-text">
              <div class="col l6 s12" >
                      <% if @contact.adress.present? %>
                    <h6> <%= @contact.adress%></h6>
                      <% end %>
                    <div>
                      <% if @contact.phone.present? %>
                          <%= @contact.phone%>
                      <% end %> 
                      <% if @contact.phone2.present? %>
                          <%= @contact.phone2%>
                      <% end %> 
                      <% if @contact.phone3.present? %>
                          <%= @contact.phone3%>
                      <% end %>
                    </div>
              </div>
              <div class="col l4 offset-l2 s12 grey-text"> 
	                <% if @contact.vk.present? %>               
	                    <%= link_to url_with_protocol(@contact.vk), class: "btn btn-social-icon btn-vk", :target => '_blank' do %>
	                      <span class="btn btn-social-icon btn-vk fa fa-vk"></span>
	                    <% end %>     
	                <% end %>
	                <% if @contact.fb.present? %>          
	                    <%= link_to url_with_protocol(@contact.fb), class: "btn btn-social-icon btn-facebook", :target => '_blank' do %>
	                      <span class="btn btn-social-icon btn-facebook fa fa-facebook"></span>
	                    <% end %>
	                <% end %>
	                <% if @contact.insta.present? %>            
	                    <%= link_to url_with_protocol(@contact.insta), class: "btn btn-social-icon btn-instagram", :target => '_blank' do %>
	                      <span class="btn btn-social-icon btn-instagram fa fa-instagram"></span>
	                    <% end %>
	                <% end %>
	                <% if @contact.twitter.present? %>          
	                    <%= link_to url_with_protocol(@contact.twitter), class: "btn btn-social-icon btn-twitter", :target => '_blank' do %>
	                      <span class="btn btn-social-icon btn-twitter fa fa-twitter"></span>
	                    <% end %>
	                <% end %>

                      <% if @contact.email.present? %>                      
                          <div><%= @contact.email%></div>  
                      <% end %>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container grey-text">
            created by dumka.maynula
            </div>
          </div>
        </footer> 
<% end %>

app/views/layouts/_header.html.erb
<style>
  .navbar-fixed ul li a {
  padding: 1.54em
}
nav ul li:hover {
   background-color: #fafafa !important;
}

nav a:hover {
  background-color: #fafafa !important;
}
nav a{
  color: #757575 !important;
}



.dropdown-content {
  min-width: 0;
  min-height: 0;
  overflow: visible !important;
}

</style>
<header>
    <div class="navbar-fixed">
      <nav style="background: rgba(255,255,255,0.5);">
        <div class="nav-wrapper"> 
          <a href="#!" class="brand-logo" style="background-color: transparent !important;"></a>
          <a href="#" data-activates="mobile-demo" class="button-collapse" style="background-color: transparent !important;"><i class="material-icons">menu</i></a>

          <ul class="right hide-on-med-and-down">
            <li class="<%= 'active' if current_page?(root_path)%>"><%= link_to t(:main), root_url%></li>
            <li class="<%= 'active' if current_page?(new_post_path) or (@post.present? and current_page?(post_path(@post))) or current_page?(posts_path)%>"><%= link_to t(:news), posts_path%></li>
            <li class="<%= 'active' if current_page?(new_album_path) or (@album.present? and current_page?(album_path(@album))) or current_page?(albums_path)%>"><%= link_to t(:gallery), albums_path%></li>
            <li class="<%= 'active' if current_page?(new_entertainment_path) or (@entertainment.present? and current_page?(entertainment_path(@entertainment))) or current_page?(entertainments_path)%>"><%= link_to t(:entertainment), entertainments_path%></li>
            <li class="<%= 'active' if current_page?(new_booking_post_path) or (@booking_post.present? and current_page?(booking_post_path(@booking_post))) or current_page?(booking_posts_path)%>"><%= link_to t(:booking), booking_posts_path%></li>
            <li class="<%= 'active' if current_page?(contacts_path)%>"><%= link_to t(:contacts), contacts_path%></li>

            <%if current_page?(locale: :ua) == false %>
              <li><%= link_to "UA", locale: :ua %></li>
            <% end %>


            <%if current_page?(locale: :ru) == false %>
              <li><%= link_to "RU", locale: :ru %></li>
            <% end %>
            <% if current_user.present? and current_user.admin? %>
            <li>
              <a class="dropdown-button" href="#!" data-activates="account-dropdown">Administrator</a>
              <ul id="account-dropdown" class="dropdown-content">
                  
                  <li class="<%= 'active' if current_page?(reservations_path)%>"><%= link_to t(:reservation_list), reservations_path%></li>
                  <li class="<%= 'active' if current_page?(contact_us_path)%>"><%= link_to t(:contact_us), contact_us_path%></li>
                  
                <% if logged_in? %>
                  <li class="<%= 'active' if (current_user.present? and current_page?(edit_user_path(current_user)))%>"><%= link_to t(:settings), edit_user_path(current_user)%></li>
                  <li><%= link_to t(:logout), logout_path, method: "delete"%></li>
                <% end %>
              </ul>
            </li>
            <% end %>
            </ul>
          </div>
      </nav>
    </div>
    <ul class="side-nav" id="mobile-demo">
      <li class="<%= 'active' if current_page?(root_path)%>"><%= link_to t(:main), root_path%></li>
      <li class="<%= 'active' if current_page?(new_post_path) or (@post.present? and current_page?(post_path(@post))) or current_page?(posts_path)%>"><%= link_to t(:news), posts_path%></li>
      <li class="<%= 'active' if current_page?(new_album_path) or (@album.present? and current_page?(album_path(@album))) or current_page?(albums_path)%>"><%= link_to t(:gallery), albums_path%></li>
      <li class="<%= 'active' if current_page?(new_entertainment_path) or (@entertainment.present? and current_page?(entertainment_path(@entertainment))) or current_page?(entertainments_path)%>"><%= link_to t(:entertainment), entertainments_path%></li>
      <li class="<%= 'active' if current_page?(new_booking_post_path) or (@booking_post.present? and current_page?(booking_post_path(@booking_post))) or current_page?(booking_posts_path)%>"><%= link_to t(:booking), booking_posts_path%></li>
      <li lass="<%= 'active' if current_page?(contacts_path)%>"><%= link_to t(:contacts), contacts_path%></li>

      <%= content_tag :li do %>
      <%= link_to "UA", locale: :ua%>
      <%end unless current_page?(locale: :ua)%>

      <%= content_tag :li do %>
      <%= link_to "RU", locale: :ru%>
      <%end unless current_page?(locale: :ru)%>
      <% if current_user.present? and current_user.admin? %>
        <li class="<%= 'active' if current_page?(reservations_path)%>"><%= link_to t(:reservation_list), reservations_path%></li>
        <li class="<%= 'active' if current_page?(contact_us_path)%>"><%= link_to t(:contact_us), contact_us_path%></li>
      <% end %>
      <% if logged_in? %>
      <li class="<%= 'active' if (current_user.present? and current_page?(edit_user_path(current_user)))%>"><%= link_to t(:settings), edit_user_path(current_user)%></li>
      <li><%= link_to t(:logout), logout_path, method: "delete"%></li>
      <% end %>
    </ul>
</header>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
<script>
// Check for jQuery.
// TODO: Fix $(dom).velocity is not function bug
if (typeof(jQuery) === 'undefined') {
  // var jQuery;
  // Check if require is a defined function.
  if (typeof(require) === 'function') {
    window.jQuery = window.$ = require('jquery');
  // Else use the dollar sign alias.
  } else {
    window.jQuery = $;
  }
};
  
</script>

<script>
(function($){
  $(function(){

    $('.button-collapse').sideNav();
    $('.parallax').parallax();
    $('.slider').slider({full_width: true});
    $('.modal').modal();
    $('.dropdown-button').dropdown({
      hover: true,
      gutter: 0, 
      }
    );
    $('.datepicker').pickadate({
      selectMonths: true, // Creates a dropdown to control month
      firstDay: 1,
      close: 'OK'
    });
    //$('.timepicker').pickatime({
    //  default: 'now',
    //  twelvehour: true, // change to 12 hour AM/PM clock from 24 hour
    //  donetext: 'OK',
    //  autoclose: false,
    //  vibrate: true // vibrate the device when dragging clock hand
    //});    
        

  }); // end of document ready
})(jQuery); // end of jQuery name space
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Your new site</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
  </head>

  <body>
  <%= render "layouts/header"%>
  <main style="margin-top: -33px;">  
    <%= yield %>
  </main>
  <%= render "layouts/footer"%>

  </body>
</html>